project:
  type: website
  render:
  - "*.qmd"
  - "!*.Rmd"
  - "!lecture*"
  resources:
    - "monash-wcd/*"
website:
  title: "emi tanaka"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "**Monash Univeristy**"
        contents:
          - monash-wcd.qmd
          - monash-cwd.qmd
          - monash-eda.qmd
  favicon: images/favicon.ico
  twitter-card:
    creator: "@statsgen"
  navbar:
    background: primary
    foreground: secondary
    logo: "images/favicon.ico"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    left: |
      <b>Dr. Emi Tanaka</b> <br>
      Senior Lecturer in Statistics<br>
      Monash University, Australia<br>
      © Copyright 2022 Emi Tanaka
    right: |
      <i class="fab fa-twitter"></i> <a href="https://twitter.com/statsgen">@statsgen</a> on Twitter <br>
      <i class="fab fa-github"></i> <a href="https://github.com/emitanaka">emitanaka</a> on GitHub <br>
      <i class="fas fa-envelope"></i> <a href="mailto:emi.tanaka@monash.edu">emi.tanaka@monash.edu</a><br>
      <i class="fas fa-map-marker-alt"></i> Clayton, Victoria, Australia
    border: true
    background: primary
format:
  html:
    theme: assets/theme.scss
    css: assets/styles.css
    include-after: |
      <link rel="stylesheet" href="assets/syntax-highlight.css">
      <link rel="stylesheet" href="assets/fontawesome-free-6.1.1-web/css/all.min.css">
      <script src="assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>




